# azure-pipelines.yml
trigger:
- main  # Adjust this to the branch you want to trigger the pipeline

pool:
  name: 'Default'
  vmImage: 'ubuntu-latest'  # Using Ubuntu to avoid Windows-specific paths

steps:
- checkout: self
  displayName: 'Checkout Code'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'  # Specify a specific Python version, e.g., '3.8'
    addToPath: true

- script: python -m venv venv
  displayName: 'Create Virtual Environment'

- script: |
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

- script: |
    source venv/bin/activate
    pytest
  displayName: 'Run Tests'

# - stage: Deploy
#   dependsOn: []  # No dependencies in this simplified example
#   jobs:
#   - job: Deploy
#     displayName: 'Deploy'
#     steps:
#     - script: echo 'Deploying to environment...'
#       displayName: 'Deploy Step'
